defmodule Phlegethon.Makeup.Style do
  @moduledoc """
  Tooling to configure and generate light/dark `Makeup` HTML stylesheets for syntax highlighting in code block components.

  If you simply wish to use a built-in theme, check out [the makeup demo](https://elixir-makeup.github.io/makeup_demo/index.html). You can see previews of each style for most supported languages.

  For inspiration on customizing overrides, check out the [built-in Makeup styles](https://github.com/elixir-makeup/makeup/blob/master/lib/makeup/styles/html/style_map.ex) and adapt them suitably.

  The stylesheets can be configured in your override file by passing a built-in or custom style function:

  ```
  defmodule MyApp.MyOverrides do
    use Phlegethon.Overrides,
      makeup_light: &Makeup.Styles.HTML.AutumnStyle.style/0,
      makeup_dark: &Makeup.Styles.HTML.MonokaiStyle.style/0
  ```

  > #### Automated Generation {: .warning}
  >
  > The stylesheet will be automatically generated by the Phlegethon compiler and inserted into `assets/css/phlegethon.css`, so aside from override configuration this module can be ignored.
  """

  @doc false
  @spec stylesheet :: binary()
  def stylesheet do
    %{light: light, dark: dark} = Phlegethon.Overrides.makeup_theme()

    light = (light && light.()) || Makeup.Styles.HTML.DefaultStyle.style()
    dark = (dark && dark.()) || Makeup.Styles.HTML.DefaultStyle.style()

    """
    /* ### MAKEUP STYLES ### */

    /* Light Style */

    #{stylesheet(light, "makeup")}

    /* Dark Style */

    #{stylesheet(dark, "dark .makeup")}
    """
  end

  defp stylesheet(style, class) do
    Makeup.stylesheet(style, class)
  end
end
